# add the following to _config.yml file
title: Burhanudin Badiuzaman
logo: /assets/img/cropped.png
#description: text below image
show_downloads: true
theme: jekyll-theme-minimal

social_links:

        twitter: "https://twitter.com/BurhanudinBZ"
        linkedin: "https://www.linkedin.com/in/burhanudin-badiuzaman4a9204161/"
